### PR TITLE
Include group information when completing password entries

### PR DESCRIPTION
**Pull request by sunesimonsen**
This change make the name shown by dmenu contain the full path
to the entry. For example if you have a password for Facebook in
the Internet group, you will be presented with Internet/Facebook instead
of just Facebook.

### CODE REVIEW

**Comment by gustavnikolaj** [comment]
> For example if you have a password for Facebook in
> the Internet group, you will be presented with Internet/Facebook instead
> of just Facebook.

I completely agree that we need this, but I would like to change it to the following:
- Show Facebook (Internet) instead of Internet/Facebook
- Only show group names for entries that do not have a unique name.

The second point, is up for discussion, but I don't see how it would make sense to have the group there if the name is unique. But there might be a use case og structure in the database that I'm not aware of.

**Comment by sunesimonsen** [comment]
I like the idea about putting the groups after the title.
I don't fully understand why you want to leave out the group information where the title is unique. There are probably was to many entries too see them all anyway. The grouping must have some kind of value too you, otherwise you could just dump all of the password in the top-level.

I'll change the pull request to show the label as you asked for.

**Comment by gustavnikolaj** [comment]
I have the following groupings in my database:
- The root has most normal passwords for often used services.
- **Network**: Contains wifi and other network credentials
- **Rarely Used**: Passwords for less often used services
- **Not yet migrated**: Passwords which I have not yet migrated to random generated passwords.
- **Email**: Credentials for email accounts

This way of grouping the entries means that I rarely have entries with non-unique names.

I realize that the pattern is a result of me using the GUI until now. This kind of grouping has less value with this kind of interface. But I will continue to use the GUIs on my smartphone and on my laptop, so I'm not sure I'm ready to change it just yet.

I don't care for the space. Dmenu is not a GUI, and the main feature is the ability to fuzzy search the entries. I was thinking about making the dmenu vertical instead of horizontal, so it's even less a question of space. But I just prefer clean and concise naming.

**Comment by sunesimonsen** [comment]
It should be pretty easy to just include the path when the title is not unique. I'll give it a shot.

**Comment by gustavnikolaj** [comment]
I realize that my use case is special, and out of the ordinary in terms of what groups are supposed to be doing. 

But do you really need to know that you are finding the Internet Service Facebook, when you dont have any other Facebooks? 

I'm not being pedantic - I'm just really having a hard time figuring out what the right thing to do here is. I can see the reasoning and argue for both cases.

I'll let you decide this one. We can always add the filtering later on if it proves to be desirable. :shipit:

**Comment by sunesimonsen** [comment]
I force pushed the code to do what you asked for. I agree it is a bit cleaner on the eyes :-)

**Comment by gustavnikolaj** [comment]
LGTM :-) Thanks alot!

What's your impression so far?

**Comment by sunesimonsen** [comment]
It is beyond awesome - and the Android app for keepass2 is also much better.

**Pull request merged**
